[env:nodemcu-32s]
board = nodemcu-32s
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
				arduino-libraries/LiquidCrystal@^1.0.7
				vase7u/LiquidMenu@^1.6.0

build_flags = -I .pio/libdeps/nodemcu-32s/LiquidCrystal/src
